### ISSUE TITLE
Crear diagrama de flujo

### ISSUE THREAD

**Issue by arielarevalo** [arielarevalo/proyectos-concurrente-2022-1#18]

**Comment by pmadrigal95** [comment]
[Diagrama de Clases](https://lucid.app/lucidchart/4f05024c-c5cf-4173-b979-b1c4477ff023/edit?viewport_loc=-320%2C-294%2C2540%2C1106%2C0_0&invitationId=inv_88e56db8-826e-495e-be4b-545498a5f2c9#)

Pendiente relaciones

**Comment by pmadrigal95** [comment]
[Diagrama de Flujo](https://lucid.app/lucidchart/dc6c67eb-7651-4607-ade5-f81e2d47b0d2/edit?viewport_loc=-69%2C-211%2C1751%2C763%2C0_0&invitationId=inv_ee64e702-cb7e-4973-9ffd-23b29ad3f2df#)
